### ISSUE TITLE
User Authentication, Parse DB

### ISSUE THREAD

**Issue by edgar-m-reyes** [Cooking-by-the-Book/Cooking-by-the-Book#10]
- [x] Get authentication function working.
  - Prompted to sign up or sign in if account is not already signed in.
  - If signed in, recipe feed page is displayed.
  - Stay signed even if app is closed.
- [x] Signing Up
  - Username and Password inputs saved into database when creating new account.
  - extra: prompted to use different username if user with same username already exists.
- [x] Signing In
  - Using correct user credentials, user is segued into recipe feed.
  - extra: notify if username or password were incorrect, prompt to try again.

**Comment by Jh0m4s** [comment]
Still need to accomplish the signing out stuff, but I have most all of the sign-in/sign-out parts!
